#!/bin/bash

./tc test.raw frmAudio
./tc frmAudio.dst frmDStar
./tc frmAudio.dmr frmDMR
./tc frmAudio.m17 frmM17
aplay -c1 -f S16_LE -r8000 test.raw
aplay -c1 -f S16_LE -r8000 frmDStar.raw
aplay -c1 -f S16_LE -r8000 frmDMR.raw
aplay -c1 -f S16_LE -r8000 frmM17.raw
